// qwik-version/src/routes/[cat]/index.tsx
import { component$ } from "@builder.io/qwik";
import { routeLoader$ } from "@builder.io/qwik-city";
import { kv } from "@vercel/kv";
import { css } from "~/styled-system/css";
import { GalleryData } from "~/routes";
import { Left } from "~/components/Left/left";
import { Right } from "~/components/Right/right";
import { Gallery } from "~/components/Gallery/gallery";

export const useKvData = routeLoader$(async (requestEvent) => {
  const cat = requestEvent.params.cat;
  const data = await kv.get(cat);
  // console.log(data);
  return data as GalleryData;
});
export default component$(() => {
  const kvData = useKvData();
  const pageData = kvData.value;
  return (
    <div
      class={css({
        display: "flex",
      })}
    >
      <Left>
        <button onClick$={() => console.log(pageData.postcards)}>asdfas</button>
        <h1 q:slot="title">{pageData.context}</h1>
        <p q:slot="text-lg">
          Featured here are some staff favorites from the Newberry’s collection.
          View more free to use and reuse images at our{" "}
          <a
            href="https://collections.newberry.org/CS.aspx?VP3=DamView&VBID=2KXJA4UE6RXM&PN=1"
            target="_blank"
            class="llines"
          >
            Postcard Gallery
          </a>
          .
        </p>
        <p class="text-base">
          The vintage postcard images featured here are free to use and reuse.
          The Newberry believes that this content is in the public domain, and
          makes these digitized copies available without requiring fees or
          permissions. For more information, see our{" "}
          <a
            href="https://www.newberry.org/policies#open-access"
            target="_blank"
            class="llines"
          >
            Open Access Policy
          </a>
          .
        </p>
      </Left>
      <Right>
        {pageData.postcards ? <Gallery data={pageData.postcards} /> : ""}
      </Right>
    </div>
  );
});

// src/routes/[cat]/+page.svelte
<script>
    import BiggerPicture from 'bigger-picture/svelte';
    import "bigger-picture/css";
    import { onMount } from 'svelte'
    import { page } from '$app/stores'
    import { imgUrl, getWidth } from '$lib'
    export let data
    // const { galleryData } = data
    const postcards = data.galleryData.items
    
    // console.log(data.)
    let bp, imageLinks

    onMount(() => {
        bp = BiggerPicture({
	        target: document.body,
        })
        imageLinks = document.querySelectorAll('#images > a')
    }) 
    function openGallery(e) {
	    e.preventDefault()
        if (e.currentTarget !== null) {
          bp.open({
            intro: "fadeup",
            items: imageLinks,
            el: e.currentTarget,
          });
        }
    }
</script>

<main>
    <div class="left">
        <div class="logo">
            <a href="/">
                <img height="60" width="300" src="NewberryLogo.png" />
            </a>
        </div>
        <header class="title">
            <h3>Free to Use and Reuse:</h3>
            <h1>
                {data.galleryData.context}
            </h1>
            <section class="text-content">
                <p class="text-lg">
                    Featured here are some staff favorites from the Newberry’s
                    collection. View more free to use and reuse images at our{" "}
                    <a
                        href="https://collections.newberry.org/CS.aspx?VP3=DamView&VBID=2KXJA4UE6RXM&PN=1"
                        target="_blank"
                        class="llines"
                    >Postcard Gallery</a>.
                </p>
                <p class="text-base">
                    The vintage postcard images featured here are free to use and
                    reuse. The Newberry believes that this content is in the public
                    domain, and makes these digitized copies available without
                    requiring fees or permissions. For more information, see our{" "}
                    <a
                        href="https://www.newberry.org/policies#open-access"
                        target="_blank"
                        class="llines"
                    >
                        Open Access Policy
                    </a>
                    .
                </p>
            </section>
        </header>
    </div>
    <div class="right" id="images">
        {#each postcards as postcard}
            <a class="tile" 
                on:click={openGallery}
                href={imgUrl(postcard.image)}
                data-img={imgUrl(postcard.image)}
                data-thumb={imgUrl(postcard.image, 'thumb')}
                data-height={postcard.height}
                data-width={postcard.width}
                data-alt={postcard.title}
                data-caption="{postcard.title}.  View at <a href='{postcard.image}'>Newberry Digital Collections</a>"
            >
                <img src={imgUrl(postcard.image, 'thumb')} 
                    width={getWidth(postcard.width, postcard.height)}
                    height={300}
                    alt={postcard.title}
                />
            </a>
        {/each}
    </div>
</main>
<style>
    .tile {
        bordeR: 0;
        margin: 0;
        padding: 0;
        height: 300px;
        display: inline-block;
    }
</style>
