// svelte-version/src/routes/+page.svelte
<script>
    import { base } from '$app/paths'
    import SecretHeader from '$lib/secret-header.svelte'
    import Masonry from '$lib/masonry.svelte'
    import Footer from '$lib/footer.svelte'
    import { getHeight, holidays } from "$lib";
    export let data
    const galleries = data.galleryData
    // console.log(data)

    const noimg = {
        title: "View even more postcards at Newberry Digital Collections",
        link: "https://collections.newberry.org/asset-management?WS=SearchResults#/DamView&VBID=2KXJA46IUGL5&PN=1&WS=SearchResults",
        pixel: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=",
        galRepreImageWidth: 300, 
        galRepreImageHeight: 400
    }

    const hGalleries = galleries.filter((f) => holidays.includes(f.title)).sort((a, b) => holidays.indexOf(a.title) - holidays.indexOf(b.title));

    // ### Non Holiday Gallery Sorting: 
    // start by filtering out the holidays
    // then a "global" sort by random
    // then loop over the array, putting the first 4 landscape postcards into arrayA (width > height), and the rest into arrayB, 
    // then, merge arrays

    let nhGalleries = galleries.filter((f) => !holidays.includes(f.title)).sort(() => Math.random() - 0.5)

    const firstFourNHGalleries = []
    const restOfNHGalleries = []

    for (let a in nhGalleries){
        if ( firstFourNHGalleries.length < 4 && nhGalleries[a].galRepreImageWidth > nhGalleries[a].galRepreImageHeight){
            firstFourNHGalleries.push(nhGalleries[a])
        } else {
            restOfNHGalleries.push(nhGalleries[a])
        }
    }

    nhGalleries = [ ...firstFourNHGalleries, ...restOfNHGalleries, noimg]

    // console.log(nhGalleries.map(nhg => [ nhg.title, nhg.galRepreImageWidth > nhg.galRepreImageHeight ? 'landscape' : 'portrait' ]))

</script>
<svelte:head>
    <title>Newberry Postcard Galleries</title>
</svelte:head>
<main>
    <SecretHeader title="Newberry Postcard Gallery" />
    <div class="left">

        <div class="logo">
            <!-- <a href="https://www.newberry.org"> -->
            <a href="{ base }/">
                <img class="biggo" src="{ base }/NewberryLogo.png" alt="Logo for the Newberry Library" height="60" width="300" />
                <img class="smallo" src="{ base }/NLogo.png" alt="Logo for the Newberry Library" height="60" width="60" />
            </a>
        </div>
        <header>
            <section class="title">
                <h1 class="">Newberry Postcard Gallery </h1>
            </section>
            <aside class="text-content">
                <p class="text-lg">
                    The vintage postcard images featured here are free to use and
                    reuse. The Newberry believes that this content is in the public
                    domain, and makes these digitized copies available without
                    requiring fees or permissions. For more information, see our{" "}
                    <a
                        href="https://www.newberry.org/policies#open-access"
                        target="_blank"
                        class="llines"
                    >
                        Open Access Policy
                    </a>
                    .
                </p>
                <p class="text-base">
                    The Newberry houses one of the largest public collections of
                    postcards and related materials in the United States. Learn more
                    at our{" "}
                    <a
                        href="https://www.newberry.org/collection/subjects/postcards"
                        target="_blank"
                        class="llines"
                    >
                        Postcards information page
                    </a>
                    , browse more than{" "}
                    <a
                        href="https://collections.newberry.org/asset-management?WS=SearchResults#/DamView&VBID=2KXJA4UET6ZH&PN=1&WS=SearchResults"
                        target="_blank"
                        class="llines"
                    >
                        50,000 digitized postcards
                    </a>{" "}
                    at Newberry Digital Collections, or explore the themed sets
                    featured here.
                </p>
                <p class="text-sm">
                    With gratitude to the Library of Congress for its{" "}
                    <a
                        href="https://www.loc.gov/free-to-use/"
                        target="_blank"
                        class="llines"
                    >
                        Free to Use and Reuse Sets
                    </a>
                    , from which this site is inspired.
                </p>
            </aside>
        </header>   

        <Footer >

                <section class="tag-button">
                <p>
                    The Newberry needs your help! Please assist with making our
                    postcard collections more accessible at 
            <a
                href="https://www.zooniverse.org/projects/newberry/postcard-tag"
                target="_blank"
                        class="llines"
            >Postcard Tag</a>
                    </p>
</section>
        </Footer>
    </div>
    <div class="right">
        <Masonry defaultDirection="start">
            {#each nhGalleries as item}
                <a href={item.link || `${base}/${item.slug}`} class={item.pixel ? "noimg" : ""} target={item.pixel ? '_blank' : '_self'} >
                    <img src="{ item.pixel ? item.pixel : item.title === 'Animated gifs' ? 'https://collections.newberry.org/AssetLink/136hd1108fjm3yp3aln81y6nenu04dqg.gif' : `https://collections.newberry.org/IIIF3/Image/${ item.title === 'Chicago' ? '2KXJ8ZSVHKQYC' : item.galRepreImageMEI}/full/300,/0/default.jpg`}" alt="a {item.title} postcard" height={getHeight( item.galRepreImageWidth, item.galRepreImageHeight )} width="300" >
                    <h3 >{item.title}</h3>
                </a>
            {/each}
        </Masonry>
        <Masonry>
            {#each hGalleries as item}
                <a class="holiday" href="{base}/{item.slug}">
                    <img src="https://collections.newberry.org/IIIF3/Image/{item.galRepreImageMEI}/full/300,/0/default.jpg" alt="a {item.title} postcard" height={getHeight( item.galRepreImageWidth, item.galRepreImageHeight )} width="300" >
                    <h3>{item.title}</h3>
                </a>
            {/each}
        </Masonry>
    </div>
</main>


<style>
    .tag-button {
        margin-inline: 16px;
        background: rgb(var(--bg-color-1));
    } 
.right {
    display: flex;
    flex-direction: column;
}
</style>

// qwik-version/src/routes/index.tsx
import { component$ } from "@builder.io/qwik";
import { routeLoader$, type DocumentHead } from "@builder.io/qwik-city";
import { kv } from "@vercel/kv";
import { Card } from "~/components/Card/card";
import { Left } from "~/components/Left/left";
import { Right } from "~/components/Right/right";
import { css } from "~/styled-system/css";

export const holidays = [
  "Valentine's Day",
  "Easter",
  "Halloween",
  "Thanksgiving",
  "Christmas",
];

export function getWidth(w: number, h: number) {
  // w:h::x:300
  return Math.round((w * 300) / h);
}

export type GalleryData = {
  title: string;
  context: string;
  slug: string;
  galMEI: string;
  galRepreImageMEI: string;
  galRepreImageHeight: number;
  galRepreImageWidth: number;
  galRepreImageTitle: string;
  postcards?: PostcardData[];
};
export type PostcardData = {
  title: string;
  mei: string;
  repImage: string;
  repImageTitle: string;
  repImageWidth: number;
  repImageHeight: number;
};

const mei = "2KXJ8ZSA9MFDO";

export const useKvData = routeLoader$(async () => {
  const data = await kv.get(mei);
  // console.log(data);
  return data as GalleryData[];
});

export default component$(() => {
  const allGalleries = useKvData();
  const holidayGalleries = allGalleries.value.filter((f) => {
    // console.log(f.title);
    return holidays.includes(f.title);
  });
  const nonHolidayGalleries = allGalleries.value.filter(
    (f) => !holidays.includes(f.title) && f.title !== "Animated gifs",
  );
  return (
    <div
      class={css({
        display: "flex",
        "& .galleries": {
          display: "flex",
          flexFlow: "row wrap",
          gap: "8px",
          marginBottom: "64px",
        },
        "& .empty-tile": {
          width: "250px",
          height: "300px",
          display: "block",
          position: "relative",
        },
        "& .empty-tile h3": {
          position: "absolute",
          top: 0,
          left: 0,
          bottom: 0,
          right: 0,
          margin: 0,
          padding: "8px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          background: "rgb(var(--fg-color-2))",
          color: "rgb(var(--bg-color-1))",
          textAlign: "center",
          fontSize: "1.5rem",
          border: "1px solid rgb(var(--fg-color-1))",
        },
        "& .notile": {
          pointerEvents: "none",
          userSelect: "none",
        },
      })}
    >
      <Left>
        <h1 q:slot="title">Newberry Postcard Gallery</h1>

        <p q:slot="text-lg">
          The vintage postcard images featured here are free to use and reuse.
          The Newberry believes that this content is in the public domain, and
          makes these digitized copies available without requiring fees or
          permissions. For more information, see our{" "}
          <a
            href="https://www.newberry.org/policies#open-access"
            target="_blank"
            class="llines"
          >
            Open Access Policy
          </a>
          .
        </p>
        <p>
          The Newberry houses one of the largest public collections of postcards
          and related materials in the United States. Learn more at our{" "}
          <a
            href="https://www.newberry.org/collection/subjects/postcards"
            target="_blank"
            class="llines"
          >
            Postcards information page
          </a>
          , browse more than{" "}
          <a
            href="https://collections.newberry.org/asset-management?WS=SearchResults#/DamView&VBID=2KXJA4UET6ZH&PN=1&WS=SearchResults"
            target="_blank"
            class="llines"
          >
            50,000 digitized postcards
          </a>{" "}
          at Newberry Digital Collections, or explore the themed sets featured
          here.
        </p>
        <p>
          The Newberry needs your help! Please assist with making our postcard
          collections more accessible:{" "}
          <a
            href="https://www.zooniverse.org/projects/newberry/postcard-tag"
            target="_blank"
            class="llines"
          >
            Postcard Tag
          </a>
        </p>
        <p q:slot="text-sm">
          With gratitude to the Library of Congress for its{" "}
          <a
            href="https://www.loc.gov/free-to-use/"
            target="_blank"
            class="llines"
          >
            Free to Use and Reuse Sets
          </a>
          , from which this site is inspired.
        </p>
      </Left>
      <Right>
        <div class="galleries">
          {nonHolidayGalleries.map((item) => (
            <Card item={item} />
          ))}
          <a
            class="tile empty-tile"
            target="_blank"
            href="https://collections.newberry.org/CS.aspx?VP3=DamView&VBID=2KXJA4UE6RXM&PN=1"
          >
            <h3>View even more postcards at Newberry Digital Collections</h3>
          </a>
        </div>

        <div class="galleries">
          <a href="/" class="htile tile notile" tabIndex={-1}>
            <img
              src="./madonna-holiday.gif"
              width={getWidth(498, 373)}
              height="300"
              alt="Madonna Ciccone dancing in a music video from the 1980s"
            />
          </a>
          {holidayGalleries.map((item) => (
            <Card item={item} holidays />
          ))}
        </div>
      </Right>
    </div>
  );
});

export const head: DocumentHead = {
  title: "Newberry Library Postcard Galleries",
  meta: [
    {
      name: "description",
      content:
        "A showcase of curated postcard galleries from the digital collections of the Newberry Library",
    },
  ],
};
